
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECIMAL = 5;
  public static final int MENOS = 7;
  public static final int MULTI = 8;
  public static final int ENTERO = 4;
  public static final int EOF = 0;
  public static final int MAS = 6;
  public static final int DIV = 9;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 2;
  public static final int OPERAR = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "OPERAR",
  "ENTERO",
  "DECIMAL",
  "MAS",
  "MENOS",
  "MULTI",
  "DIV"
  };
}

